### ISSUE TITLE
基于 Android Q 的 MIUI 11 点击 “import config” 闪退

### ISSUE THREAD

**Issue by zengmiaokun** [ccg2018/ClashA#36]
java.lang.NullPointerException: Attempt to get length of null array
	at me.rosuh.filepicker.FilePickerActivity.isLotsOfFiles(FilePickerActivity.kt:400)
	at me.rosuh.filepicker.FilePickerActivity.access$isLotsOfFiles(FilePickerActivity.kt:41)
	at me.rosuh.filepicker.FilePickerActivity$prepareLauncher$1.invokeSuspend(FilePickerActivity.kt:131)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)

**Comment by zengmiaokun** [comment]
目前用类原生的系统是正常的，但是用开发版MIUI11暂时会闪退。

**Comment by tindy2013** [comment]
@zengmiaokun filepicker对android q有些兼容性问题 等上游修复

**Comment by xuhaoyang** [comment]
@zengmiaokun 已经修复

**Comment by zengmiaokun** [comment]
最新版已经解决了，谢谢了。
